spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: vcrop
    password: sa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
bot:
  username: vcrophoroscope
  token: 5301253935:AAHJud48hldAdcvVvhB66-fp0tLWBSLWUNc